/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Sistema;

import Usuarios.Usuario;
import Usuarios.UsuarioSuperAdmin;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author dz
 */
public class PanelUsuariosExistentes extends javax.swing.JPanel {

    /**
     * Creates new form PanelUsuariosExistentes
     */
    public PanelUsuariosExistentes(UsuarioSuperAdmin user) {
        initComponents();
        diseño(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconoUusario = new javax.swing.JLabel();
        labelNOmbre = new javax.swing.JLabel();
        labelCOntra = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        labelSucursal = new javax.swing.JLabel();
        labelRol = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 255, 102));

        iconoUusario.setBackground(new java.awt.Color(51, 255, 102));
        iconoUusario.setOpaque(true);

        labelNOmbre.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelNOmbre.setForeground(new java.awt.Color(0, 0, 0));
        labelNOmbre.setText("Nombre: Usuario");

        labelCOntra.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelCOntra.setForeground(new java.awt.Color(0, 0, 0));
        labelCOntra.setText("Contraseña:");

        labelCorreo.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelCorreo.setForeground(new java.awt.Color(0, 0, 0));
        labelCorreo.setText("Correo: ");

        labelSucursal.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelSucursal.setForeground(new java.awt.Color(0, 0, 0));
        labelSucursal.setText("Sucursal:  - - - - -");

        labelRol.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelRol.setForeground(new java.awt.Color(0, 0, 0));
        labelRol.setText("Rol: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconoUusario, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelNOmbre, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(labelCOntra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSucursal, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelRol, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconoUusario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNOmbre)
                            .addComponent(labelRol))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCorreo)
                            .addComponent(labelSucursal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelCOntra)
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconoUusario;
    private javax.swing.JLabel labelCOntra;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelNOmbre;
    private javax.swing.JLabel labelRol;
    private javax.swing.JLabel labelSucursal;
    // End of variables declaration//GEN-END:variables


    
    private void diseño(UsuarioSuperAdmin user){
        
        
        
        ImageIcon imagen = new ImageIcon(getClass().getResource("/imagen/acceso.png"));
        imagen = new ImageIcon(imagen.getImage().getScaledInstance((90), (90), Image.SCALE_SMOOTH));
        iconoUusario.setIcon(imagen);
        
        
        
        labelNOmbre.setText("Nombre: " + user.getNombre());
        labelCOntra.setText( "Contraseña: " + user.getPassword());
        labelCorreo.setText("Correo: "+ user.getCorreo());
        labelRol.setText("Rol: "+ user.getRol());
        
        
        if(user.getSucursal() == null || user.getSucursal() == ""){
            
            labelSucursal.setText("Sin Sucursal");
        }else{
        
            labelSucursal.setText("Sucursal: "+user.getSucursal());
        }
    }
    
    

}
