package Partida;

import Usuarios.Ingrediente;

/**
 *
 * @author dz
 */
public class InformaciónIngrediente extends javax.swing.JPanel {

    
    private Ingrediente ingrediente;
    
    /**
     * Creates new form Ingredientes
     */
    public InformaciónIngrediente(Ingrediente ingrediente) {
        this.ingrediente = ingrediente;
        initComponents();
        editarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconoProducto = new javax.swing.JLabel();
        nameIgrediente = new javax.swing.JLabel();
        cantidadIngrediente = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));

        iconoProducto.setBackground(new java.awt.Color(255, 255, 255));
        iconoProducto.setForeground(new java.awt.Color(255, 153, 255));
        iconoProducto.setOpaque(true);

        nameIgrediente.setForeground(new java.awt.Color(0, 0, 0));
        nameIgrediente.setText("Nombre");

        cantidadIngrediente.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        cantidadIngrediente.setForeground(new java.awt.Color(0, 0, 0));
        cantidadIngrediente.setText(" x 10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameIgrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cantidadIngrediente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameIgrediente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cantidadIngrediente))
                    .addComponent(iconoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cantidadIngrediente;
    private javax.swing.JLabel iconoProducto;
    private javax.swing.JLabel nameIgrediente;
    // End of variables declaration//GEN-END:variables

    
    private void editarComponentes(){
        nameIgrediente.setText(ingrediente.getNombre());
        cantidadIngrediente.setText("x "+ Integer.toString(ingrediente.getCantidad()));
        
    }
    

}
