package Partida;

import Sistema.Pedido;
import Usuarios.Ingrediente;
import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 * @author dz
 */
public class InformacionPedido extends javax.swing.JPanel {

    
    private Pedido pedido;
    
    /**
     * Creates new form Pedidos
     * @param pedido
     */
    
    public InformacionPedido(Pedido pedido) {
        
        this.pedido = pedido;
        initComponents();
        infoPedido();
        crearIngredientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idPedido = new javax.swing.JLabel();
        iconoPedido = new javax.swing.JLabel();
        fechaPedido = new javax.swing.JLabel();
        botonAceptarPedido = new javax.swing.JButton();
        botonRechazar = new javax.swing.JButton();
        scrollIngredientes = new javax.swing.JScrollPane();
        contenedorIngredientes = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(205, 270));
        setMinimumSize(new java.awt.Dimension(205, 270));

        idPedido.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        idPedido.setForeground(new java.awt.Color(0, 0, 0));
        idPedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idPedido.setText("Pedido #!");

        iconoPedido.setBackground(new java.awt.Color(255, 255, 255));
        iconoPedido.setOpaque(true);

        fechaPedido.setBackground(new java.awt.Color(255, 255, 255));
        fechaPedido.setForeground(new java.awt.Color(0, 51, 51));
        fechaPedido.setText("Fecha Pedido");
        fechaPedido.setOpaque(true);

        botonAceptarPedido.setBackground(new java.awt.Color(153, 255, 153));
        botonAceptarPedido.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        botonAceptarPedido.setForeground(new java.awt.Color(0, 0, 0));
        botonAceptarPedido.setText("ACEPTAR");

        botonRechazar.setBackground(new java.awt.Color(255, 153, 153));
        botonRechazar.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        botonRechazar.setForeground(new java.awt.Color(0, 0, 0));
        botonRechazar.setText("RECHAZAR");
        botonRechazar.setMargin(new java.awt.Insets(0, 0, 0, 0));

        scrollIngredientes.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        /*
        contenedorIngredientes.setLayout(new javax.swing.BoxLayout(contenedorIngredientes, javax.swing.BoxLayout.LINE_AXIS));
        */
        contenedorIngredientes.setLayout(new javax.swing.BoxLayout(contenedorIngredientes, javax.swing.BoxLayout.Y_AXIS));
        scrollIngredientes.setViewportView(contenedorIngredientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(idPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(iconoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(fechaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonAceptarPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonRechazar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(scrollIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(idPedido)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(fechaPedido)))
                .addGap(6, 6, 6)
                .addComponent(scrollIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonAceptarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonRechazar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptarPedido;
    private javax.swing.JButton botonRechazar;
    private javax.swing.JPanel contenedorIngredientes;
    private javax.swing.JLabel fechaPedido;
    private javax.swing.JLabel iconoPedido;
    private javax.swing.JLabel idPedido;
    private javax.swing.JScrollPane scrollIngredientes;
    // End of variables declaration//GEN-END:variables


    private void infoPedido(){
    
        fechaPedido.setText(pedido.getFechaPedido().toString());
        idPedido.setText("Pedido "+pedido.getIdPedido());        
        
        ImageIcon imagen = new ImageIcon(getClass().getResource("/imagen/pizza.png"));
        imagen = new ImageIcon(imagen.getImage().getScaledInstance((60), (60), Image.SCALE_SMOOTH));
        iconoPedido.setIcon(imagen);

    }
    
    private void minipanelIngrediente(Ingrediente ingrediente){
        
        InformaciónIngrediente panelIngrediente = new InformaciónIngrediente(ingrediente);
        
        contenedorIngredientes.add(panelIngrediente);
        
        
        
    }
    
    private void crearIngredientes(){
        
        for(int i = 0; i < pedido.getIngredientes().getTamaño(); i++){
            Ingrediente ingrediente = (Ingrediente) pedido.getIngredientes().seleccionarNodo(i).getObjeto();
            minipanelIngrediente(ingrediente);
        }
        
    }
    
    
    public void agregarEventoBoton(ActionListener evento){
        botonAceptarPedido.addActionListener(evento);
    }
    

}
