/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Partida;

import Sistema.DatosPartida;
import java.awt.event.ActionListener;

/**
 *
 * @author dz
 */
public class PanelResultados extends javax.swing.JPanel {

    /**
     * Creates new form PanelResultados
     */
    private DatosPartida datosPartida;
    
    public PanelResultados(DatosPartida datosPartida) {
        initComponents();
        
        this.datosPartida = datosPartida;
        diseño();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNOmbre = new javax.swing.JLabel();
        labelTurnoTerminado = new javax.swing.JLabel();
        etiquetaNOmbre = new javax.swing.JLabel();
        labelSucursal = new javax.swing.JLabel();
        etiquetaSucursal = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        etiquetaID = new javax.swing.JLabel();
        labelPuntos = new javax.swing.JLabel();
        etiquetaPuntos = new javax.swing.JLabel();
        labelPedidos = new javax.swing.JLabel();
        etiquetaPedidos = new javax.swing.JLabel();
        labelTiempo = new javax.swing.JLabel();
        etiquetsTiempo = new javax.swing.JLabel();
        iconoPizza = new javax.swing.JLabel();
        botonMenu = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 255, 102));

        labelNOmbre.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelNOmbre.setForeground(new java.awt.Color(0, 0, 0));
        labelNOmbre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelNOmbre.setText("NOMBRE:");

        labelTurnoTerminado.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        labelTurnoTerminado.setForeground(new java.awt.Color(0, 0, 0));
        labelTurnoTerminado.setText("Turno Terminado");

        etiquetaNOmbre.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaNOmbre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiquetaNOmbre.setText("Nombre Jugador");

        labelSucursal.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelSucursal.setForeground(new java.awt.Color(0, 0, 0));
        labelSucursal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelSucursal.setText("Sucursal:");

        etiquetaSucursal.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaSucursal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiquetaSucursal.setText("Sucursal");

        labelID.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelID.setForeground(new java.awt.Color(0, 0, 0));
        labelID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelID.setText("ID:");

        etiquetaID.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiquetaID.setText("ID");

        labelPuntos.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        labelPuntos.setForeground(new java.awt.Color(0, 0, 0));
        labelPuntos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPuntos.setText("Puntos Obtenidos:");

        etiquetaPuntos.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        etiquetaPuntos.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaPuntos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiquetaPuntos.setText("1000");

        labelPedidos.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        labelPedidos.setForeground(new java.awt.Color(0, 0, 0));
        labelPedidos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPedidos.setText("Pedidos Completados:");

        etiquetaPedidos.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        etiquetaPedidos.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaPedidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiquetaPedidos.setText("5");

        labelTiempo.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        labelTiempo.setForeground(new java.awt.Color(0, 0, 0));
        labelTiempo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTiempo.setText("Tiempo:");

        etiquetsTiempo.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        etiquetsTiempo.setForeground(new java.awt.Color(0, 0, 0));
        etiquetsTiempo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiquetsTiempo.setText("10 segundos");

        botonMenu.setBackground(new java.awt.Color(102, 255, 102));
        botonMenu.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        botonMenu.setForeground(new java.awt.Color(0, 0, 0));
        botonMenu.setText("Menú ");
        botonMenu.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(etiquetaSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNOmbre, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(etiquetaNOmbre, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelID, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(etiquetaID, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconoPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(labelTurnoTerminado, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(botonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(etiquetsTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(etiquetaPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelPuntos)
                                    .addGap(18, 18, 18)
                                    .addComponent(etiquetaPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(labelTurnoTerminado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNOmbre)
                            .addComponent(etiquetaNOmbre, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSucursal)
                            .addComponent(etiquetaSucursal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelID)
                            .addComponent(etiquetaID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelPuntos)
                                    .addComponent(etiquetaPuntos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelPedidos)
                                    .addComponent(etiquetaPedidos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelTiempo)
                                    .addComponent(etiquetsTiempo))
                                .addGap(101, 101, 101))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(iconoPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonMenu;
    private javax.swing.JLabel etiquetaID;
    private javax.swing.JLabel etiquetaNOmbre;
    private javax.swing.JLabel etiquetaPedidos;
    private javax.swing.JLabel etiquetaPuntos;
    private javax.swing.JLabel etiquetaSucursal;
    private javax.swing.JLabel etiquetsTiempo;
    private javax.swing.JLabel iconoPizza;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelNOmbre;
    private javax.swing.JLabel labelPedidos;
    private javax.swing.JLabel labelPuntos;
    private javax.swing.JLabel labelSucursal;
    private javax.swing.JLabel labelTiempo;
    private javax.swing.JLabel labelTurnoTerminado;
    // End of variables declaration//GEN-END:variables

    
    
    public void eventoRegresarMenu(ActionListener evento){
    
        botonMenu.addActionListener(evento);
    
    }
    
    private void diseño(){
    
        etiquetaNOmbre.setText(datosPartida.getIdPlayer().getNombre());
        etiquetaSucursal.setText(datosPartida.getIdPlayer().getSucursal().getNombre());
        etiquetaID.setText(datosPartida.getIdPlayer().getNombre());
        etiquetaPuntos.setText(Integer.toString(datosPartida.getPuntos()));
        etiquetsTiempo.setText(Integer.toString(datosPartida.getTiempo()));
        etiquetaPedidos.setText(Integer.toString(datosPartida.getPedidosCompletados()));
        
    
    }

}
