package Partida;

import PanelPartida.PanelProductos;
import Usuarios.Ingrediente;
import Sistema.Pedido;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author dz
 */
public class PanelPedidoAceptado extends javax.swing.JPanel {

    private PanelProductos panelProductos;
    private ActionListener eventoEntrega;
    private Pedido pedido;
    
    public PanelPedidoAceptado(Pedido pedido) {
                
        this.pedido = pedido;
        initComponents();
        diseñoCOmponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorIngredientes = new javax.swing.JPanel();
        imagenPizza = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonHornear = new javax.swing.JButton();
        progresoHorno = new javax.swing.JProgressBar();
        jSeparator1 = new javax.swing.JSeparator();
        labelTiempo = new javax.swing.JLabel();
        labelTIempoLimite = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 153));
        setPreferredSize(new java.awt.Dimension(600, 430));

        contenedorIngredientes.setBackground(new java.awt.Color(204, 255, 204));
        contenedorIngredientes.setMaximumSize(new java.awt.Dimension(32767, 165));
        contenedorIngredientes.setMinimumSize(new java.awt.Dimension(560, 165));
        contenedorIngredientes.setName(""); // NOI18N
        contenedorIngredientes.setPreferredSize(new java.awt.Dimension(560, 160));
        contenedorIngredientes.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        imagenPizza.setBackground(new java.awt.Color(153, 255, 153));
        imagenPizza.setForeground(new java.awt.Color(153, 255, 153));
        imagenPizza.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID Pedido:");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("001");

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Fecha 10/12/2203");

        botonHornear.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        botonHornear.setForeground(new java.awt.Color(0, 0, 0));
        botonHornear.setText("Hornear");
        botonHornear.setEnabled(false);
        botonHornear.setBackground(new java.awt.Color(51,255,153));
        botonHornear.setMargin(new java.awt.Insets(0, 0, 0, 0));

        progresoHorno.setBackground(new java.awt.Color(51, 51, 51));
        progresoHorno.setForeground(new java.awt.Color(204, 255, 153));
        progresoHorno.setValue(1);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        labelTiempo.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelTiempo.setForeground(new java.awt.Color(0, 0, 0));
        labelTiempo.setText("Tiempo: ");

        labelTIempoLimite.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        labelTIempoLimite.setForeground(new java.awt.Color(0, 0, 0));
        labelTIempoLimite.setText("Tiempo Límite: 100");

        botonCancelar.setBackground(new java.awt.Color(255, 204, 204));
        botonCancelar.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(0, 0, 0));
        botonCancelar.setText("Cancelar");
        botonCancelar.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(contenedorIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(imagenPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel4)
                    .addComponent(labelTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTIempoLimite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(progresoHorno, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(botonHornear, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTIempoLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTiempo))
                    .addComponent(jSeparator1)
                    .addComponent(imagenPizza, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonHornear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progresoHorno, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(contenedorIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        contenedorIngredientes.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonHornear;
    private javax.swing.JPanel contenedorIngredientes;
    private javax.swing.JLabel imagenPizza;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelTIempoLimite;
    private javax.swing.JLabel labelTiempo;
    private javax.swing.JProgressBar progresoHorno;
    // End of variables declaration//GEN-END:variables


    
    private void diseñoCOmponentes(){
        ImageIcon imagen = new ImageIcon(getClass().getResource("/imagen/pizza 3.png"));
        imagen = new ImageIcon(imagen.getImage().getScaledInstance((160), (160), Image.SCALE_SMOOTH));
        imagenPizza.setIcon(imagen);
        
        imagen = new ImageIcon(getClass().getResource("/imagen/horno.png"));
        imagen = new ImageIcon(imagen.getImage().getScaledInstance((24), (24), Image.SCALE_SMOOTH));
        botonHornear.setIcon(imagen);
        
        
    }
    
    public void colocarTiempoLimite(int tiempo){
        labelTIempoLimite.setText("Tiempo Límite: " + tiempo);
    
    }
    
    public SubPanelIngredientes agregarIngredientes(Ingrediente ingrediente){
        
        
        SubPanelIngredientes controlIngrediente = new SubPanelIngredientes(ingrediente);
        contenedorIngredientes.add(controlIngrediente);
        
        return controlIngrediente;
    }

    public void eliminarComponente(SubPanelIngredientes controlIngrediente){
        
        contenedorIngredientes.remove(controlIngrediente);
        revalidate();
        repaint();
        
        
    }
    
    public void activarHorno(boolean activar) {
        
        botonHornear.setEnabled(activar);
        
       
    }
    
    
  
    
    
    public void eventoBotonHornear(ActionListener evento){
        
        botonHornear.addActionListener(evento);
    }
    

    public void configurarBarraDeProgreso(int maximo) {
        
        progresoHorno.setMaximum(maximo);
        progresoHorno.setValue(0);
        
    }
    
    
    public void actualizarBarraHorno(int valor){
        progresoHorno.setValue(valor);
    
    }
            
    
    public void actualizarTiempo(int segundos){
        labelTiempo.setText("Tiempo: " + segundos);
        
    }
    
    
    
    public void activarEntrega(){
        
        for (ActionListener eventos : botonHornear.getActionListeners()) {
            botonHornear.removeActionListener(eventos);
        }
        
        botonHornear.setEnabled(true);
        botonHornear.setText("Entregar");
        botonHornear.setBackground(new Color(0,255,204));
        
        ImageIcon imagen = new ImageIcon(getClass().getResource("/imagen/caja pizza.png"));
        imagen = new ImageIcon(imagen.getImage().getScaledInstance((24), (24), Image.SCALE_SMOOTH));
        botonHornear.setIcon(imagen);
        
        pedido.setEstado("ENTREGADO");
        
        botonHornear.addActionListener(eventoEntrega);
    }
    
    public void agregarEventoEntregar(ActionListener evento){
    }
    
    
    public void pedidoNoEntregado(){
        
        //SE ELIMINA EL EVENTO "HORNEAR"
        
        for (ActionListener eventos : botonHornear.getActionListeners()) {
            botonHornear.removeActionListener(eventos);
        }

        
        botonHornear.setEnabled(true);
        botonHornear.setText("Terminar");
        botonHornear.setBackground(new Color(255,153,153));
        
        ImageIcon imagen = new ImageIcon(getClass().getResource("/imagen/caja pizza.png"));
        imagen = new ImageIcon(imagen.getImage().getScaledInstance((24), (24), Image.SCALE_SMOOTH));
        botonHornear.setIcon(imagen);
        
        pedido.setEstado("NO_ENTREGADO");
        
        botonHornear.addActionListener(eventoEntrega);
        
        
        
        
        
    }
    
    //SETTERS AN D GETTERS
    public JPanel getContenedorIngredientes() {
        return contenedorIngredientes;
    }

    public void setEventoEntrega(ActionListener eventoEntrega) {
        this.eventoEntrega = eventoEntrega;
    }
    
    public void setEventoCancelar(ActionListener eventoCAncelar){
        botonCancelar.addActionListener(eventoCAncelar);
        pedido.setEstado("CANCELADO");
    }

    public Pedido getPedido() {
        return pedido;
    }


}