/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Partida;

import Usuarios.Usuario;
import java.awt.event.ActionListener;

/**
 *
 * @author dz
 */
public class PanelMenuJugador extends javax.swing.JPanel {

    
    private Usuario player;
    
    /**
     * Creates new form PanelMenuJugadores
     */
    public PanelMenuJugador(Usuario player) {
        this.player = player;
        initComponents();
        diseño();
                
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelIconoPlayer = new javax.swing.JLabel();
        labelHIstorial = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelSucursal = new javax.swing.JLabel();
        botonPartida = new javax.swing.JButton();
        scrollHistorial = new javax.swing.JScrollPane();
        panelHistorial = new javax.swing.JPanel();
        labelID = new javax.swing.JLabel();
        botonMenu = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setPreferredSize(new java.awt.Dimension(950, 680));

        labelIconoPlayer.setBackground(new java.awt.Color(153, 255, 153));
        labelIconoPlayer.setOpaque(true);

        labelHIstorial.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelHIstorial.setForeground(new java.awt.Color(0, 0, 0));
        labelHIstorial.setText("Historial de Partidas");

        labelNombre.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(0, 0, 0));
        labelNombre.setText("Nombre: ");

        labelSucursal.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        labelSucursal.setForeground(new java.awt.Color(0, 0, 0));
        labelSucursal.setText("Sucursal centro");

        botonPartida.setBackground(new java.awt.Color(51, 255, 204));
        botonPartida.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        botonPartida.setForeground(new java.awt.Color(0, 0, 0));
        botonPartida.setText("Iniciar Partida");

        scrollHistorial.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        javax.swing.GroupLayout panelHistorialLayout = new javax.swing.GroupLayout(panelHistorial);
        panelHistorial.setLayout(panelHistorialLayout);
        panelHistorialLayout.setHorizontalGroup(
            panelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );
        panelHistorialLayout.setVerticalGroup(
            panelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );

        scrollHistorial.setViewportView(panelHistorial);

        labelID.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelID.setForeground(new java.awt.Color(0, 0, 0));
        labelID.setText("ID Jugador: ");

        botonMenu.setBackground(new java.awt.Color(204, 255, 204));
        botonMenu.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        botonMenu.setForeground(new java.awt.Color(0, 0, 0));
        botonMenu.setText("Menu");
        botonMenu.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHIstorial, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botonMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelIconoPlayer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(botonPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(botonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelIconoPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(botonPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(140, 140, 140)
                .addComponent(labelHIstorial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonMenu;
    private javax.swing.JButton botonPartida;
    private javax.swing.JLabel labelHIstorial;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelIconoPlayer;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelSucursal;
    private javax.swing.JPanel panelHistorial;
    private javax.swing.JScrollPane scrollHistorial;
    // End of variables declaration//GEN-END:variables

    
    private void diseño(){
        labelNombre.setText("Nombre: "+ player.getNombre());
        labelID.setText("ID Jugador: "+ player.getId());
        labelSucursal.setText(player.getSucursal().getNombre());
        
        
    }
    
    
    public void eventoRegresarMenu(ActionListener evento) {
        botonMenu.addActionListener(evento);
        
    }
    
    public void eventoIniciarPartida(ActionListener evento){
        botonPartida.addActionListener(evento);
        
    }
}
