/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelPartida;

import Partida.InformacionPedido;
import Sistema.Pedido;
import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import javax.swing.Box;
import javax.swing.BoxLayout;

/**
 *
 * @author dz
 */
public class PanelPedidos extends javax.swing.JPanel {

    /**
     * Creates new form PanelPedidos
     */
    public PanelPedidos() {
        initComponents();
        setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(153, 255, 102));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public InformacionPedido agregarPedido(Pedido pedido, ActionListener evento){
        
        add(Box.createVerticalStrut(10));
        
        InformacionPedido nuevoPedido = new InformacionPedido(pedido);
        this.add(nuevoPedido);
        nuevoPedido.agregarEventoBoton(evento);
        nuevoPedido.agregarEventoBoton(e -> elimiarPedido(nuevoPedido));
        
        revalidate();
        repaint();
        System.out.println("???");
        
        
        return nuevoPedido;
    }

    
    private void elimiarPedido(InformacionPedido pedidoInformacions){
    
        remove(pedidoInformacions);
    
    }

}



